### PR TITLE
Use merge_attributes in delegation factory

### PR DESCRIPTION
**Pull request by jinjagit**
We should probably do this for other factories too.

### CODE REVIEW

**Review by oliverbarnes — CHANGES_REQUESTED** [review]
Yeah, we should do it for any factories building associations and sharing attributes, like `vote_factory`

Would you also capitalize the beginning of the commit sentence, please? I've edited the PR title. 👮‍♂️

**Comment by jinjagit** [comment]
> Yeah, we should do it for any factories building associations and sharing attributes, like `vote_factory`
> 
In this PR?

**Comment by oliverbarnes** [comment]
Yes please - I asked for a separate PR also to add this, as it's outside the scope of the other one

**Review by oliverbarnes — CHANGES_REQUESTED** [review]
`delegation_factory` also has associations with shared attrs

**Comment by jinjagit** [comment]
I have now added merge_attributes to all the factories.

**Comment by jinjagit** [comment]
Hold off one second on the (re)review. need to run mix format!

**Review by oliverbarnes — APPROVED** [review]

**Pull request merged**
